// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "economia/clasificacion.mdx": () => import("../content/docs/economia/clasificacion.mdx?collection=docs"), "economia/configurar-moneda.mdx": () => import("../content/docs/economia/configurar-moneda.mdx?collection=docs"), "economia/index.mdx": () => import("../content/docs/economia/index.mdx?collection=docs"), "economia/tienda.mdx": () => import("../content/docs/economia/tienda.mdx?collection=docs"), "economia/trabajos.mdx": () => import("../content/docs/economia/trabajos.mdx?collection=docs"), "moderacion/automod.mdx": () => import("../content/docs/moderacion/automod.mdx?collection=docs"), "moderacion/casos.mdx": () => import("../content/docs/moderacion/casos.mdx?collection=docs"), "moderacion/comandos.mdx": () => import("../content/docs/moderacion/comandos.mdx?collection=docs"), "moderacion/index.mdx": () => import("../content/docs/moderacion/index.mdx?collection=docs"), "moderacion/logs.mdx": () => import("../content/docs/moderacion/logs.mdx?collection=docs"), "niveles/canal-subida.mdx": () => import("../content/docs/niveles/canal-subida.mdx?collection=docs"), "niveles/configurar-xp.mdx": () => import("../content/docs/niveles/configurar-xp.mdx?collection=docs"), "niveles/index.mdx": () => import("../content/docs/niveles/index.mdx?collection=docs"), "niveles/multiplicadores.mdx": () => import("../content/docs/niveles/multiplicadores.mdx?collection=docs"), "niveles/roles-recompensa.mdx": () => import("../content/docs/niveles/roles-recompensa.mdx?collection=docs"), "primeros-pasos/index.mdx": () => import("../content/docs/primeros-pasos/index.mdx?collection=docs"), "primeros-pasos/instalacion.mdx": () => import("../content/docs/primeros-pasos/instalacion.mdx?collection=docs"), "primeros-pasos/permisos.mdx": () => import("../content/docs/primeros-pasos/permisos.mdx?collection=docs"), "primeros-pasos/primer-comando.mdx": () => import("../content/docs/primeros-pasos/primer-comando.mdx?collection=docs"), "musica/comandos.mdx": () => import("../content/docs/musica/comandos.mdx?collection=docs"), "musica/filtros.mdx": () => import("../content/docs/musica/filtros.mdx?collection=docs"), "musica/fuentes.mdx": () => import("../content/docs/musica/fuentes.mdx?collection=docs"), "musica/index.mdx": () => import("../content/docs/musica/index.mdx?collection=docs"), "musica/permisos-dj.mdx": () => import("../content/docs/musica/permisos-dj.mdx?collection=docs"), "tickets/categorias.mdx": () => import("../content/docs/tickets/categorias.mdx?collection=docs"), "tickets/gestion.mdx": () => import("../content/docs/tickets/gestion.mdx?collection=docs"), "tickets/index.mdx": () => import("../content/docs/tickets/index.mdx?collection=docs"), "tickets/panel-tickets.mdx": () => import("../content/docs/tickets/panel-tickets.mdx?collection=docs"), "tickets/transcripciones.mdx": () => import("../content/docs/tickets/transcripciones.mdx?collection=docs"), }),
};
export default browserCollections;